In [1]:
import numpy as np

Two samples with three inputs. Two perceptrons without bias.

In [7]:
inputs = np.array(
    [[-1, 1, -2],
     [1, -1, 1]])
weights = np.array(
    [[1, 2, 5],
     [3, 4, 6]])

Inputs dot with weights tanspose would show four results (2 samples * 2 perceptrons)

In [8]:
inputs @ weights.T

array([[ -9, -11],
       [  4,   5]])

Now, three samples with four inputs each. Three peceptrons with two layers.
This shows 15 results (5 samples * 3 perceptrons) for each layer

In [12]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5 , 2.7, 3.3, -0.8],
          [0.4, 3, 2, -3],
          [-1, -3, 6, 3]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5 , 0.12, -0.33],
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer1_outputs)
print(layer2_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]
 [ 0.48   2.49  -2.684]
 [-0.6    5.29   5.2  ]]
[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]
 [-2.6426   2.94452  1.45542]
 [ 0.7994   1.2188   2.9497 ]]
